### ISSUE TITLE
CS:GO Weapon Paints doesnt' work

### ISSUE THREAD

**Issue by nextedoff** [Franc1sco/Franug-Weapon_Paints#10]
Hola guys! I have a big problem, when I type !ws nothing happens, I mean table doesn't appear. So, I like a experienced guy, checked logs, there I can see:
`L 02/16/2016 - 12:07:31: Query CREATE TABLE IF NOT EXISTS weaponpaints (playername varchar(128) NOT NULL, steamid varchar(32) NOT NULL, last_accountuse int(64) NOT NULL, negev varchar(64) NOT NULL DEFAULT 'none', m249 varchar(64) NOT NULL DEFAULT 'none', bizon varchar(64) NOT NULL DEFAULT 'none', p90 varchar(64) NOT NULL DEFAULT 'none', scar20 varchar(64) NOT NULL DEFAULT 'none', g3sg1 varchar(64) NOT NULL DEFAULT 'none',m4a1 varchar(64) NOT NULL DEFAULT 'none',m4a1_silencer varchar(64) NOT NULL DEFAULT 'none',ak47 varchar(64) NOT NULL DEFAULT 'none',aug varchar(64) NOT NULL DEFAULT 'none',galilar varchar(64) NOT NULL DEFAULT 'none',awp varchar(64) NOT NULL DEFAULT 'none',sg556 varchar(64) NOT NULL DEFAULT 'none',ump45 varchar(64) NOT NULL DEFAULT 'none',mp7 varchar(64) NOT NULL DEFAULT 'none',famas varchar(64) NOT NULL DEFAULT 'none',mp9 varchar(64) NOT NULL DEFAULT 'none',mac10 varchar(64) NOT NULL DEFAULT 'none',ssg08 varchar(64) NOT NULL DEFAULT 'none',nova varchar(64) NOT NULL DEFAULT 'none',xm1014 varchar(64) NOT NULL DEFAULT 'none',sawedoff varchar(64) NOT NULL DEFAULT 'none',mag7 varchar(64) NOT NULL DEFAULT 'none',elite varchar(64) NOT NULL DEFAULT 'none',deagle varchar(64) NOT NULL DEFAULT 'none',tec9 varchar(64) NOT NULL DEFAULT 'none',fiveseven varchar(64) NOT NULL DEFAULT 'none',cz75a varchar(64) NOT NULL DEFAULT 'none',glock varchar(64) NOT NULL DEFAULT 'none',usp_silencer varchar(64) NOT NULL DEFAULT 'none',p250 varchar(64) NOT NULL DEFAULT 'none',hkp2000 varchar(64) NOT NULL DEFAULT 'none',bayonet varchar(64) NOT NULL DEFAULT 'none',knife_gut varchar(64) NOT NULL DEFAULT 'none',knife_flip varchar(64) NOT NULL DEFAULT 'none',knife_m9_bayonet varchar(64) NOT NULL DEFAULT 'none',knife_karambit varchar(64) NOT NULL DEFAULT 'none',knife_tactical varchar(64) NOT NULL DEFAULT 'none',knife_butterfly varchar(64) NOT NULL DEFAULT 'none',c4 varchar(64) NOT NULL DEFAULT 'none',knife_falchion varchar(64) NOT NULL DEFAULT 'none',knife_push varchar(64) NOT NULL DEFAULT 'none',revolver varchar(64) NOT NULL DEFAULT 'none',favorite1 varch
L 02/16/2016 - 12:08:49: Query SELECT * FROM weaponpaints WHERE steamid = 'STEAM_1:0:76398454'
L 02/16/2016 - 12:09:29: Query UPDATE weaponpaints SET last_accountuse = 1455610169, playername = 'Nexted' WHERE steamid = 'STEAM_1:0:76398454';
L 02/16/2016 - 12:16:14: Query SELECT * FROM weaponpaints WHERE steamid = 'STEAM_1:0:76398454'
L 02/16/2016 - 12:17:37: Query UPDATE weaponpaints SET last_accountuse = 1455610657, playername = 'Nexted' WHERE steamid = 'STEAM_1:0:76398454';
L 02/16/2016 - 12:17:42: Query SELECT * FROM weaponpaints WHERE steamid = 'STEAM_1:0:76398454'
L 02/16/2016 - 12:20:34: Query UPDATE weaponpaints SET last_accountuse = 1455610834, playername = 'Nexted' WHERE steamid = 'STEAM_1:0:76398454';
`

It looks nice, everything looks fine, but table doesn't appear. And every time, when I restart server I see this one - first line:
`L 02/16/2016 - 12:30:23: Query CREATE TABLE IF NOT EXISTS weaponpaints (playername varchar(128) NOT NULL, steamid varchar(32) NOT NULL, last_accountuse int(64) NOT NULL, negev varchar(64) NOT NULL DEFAULT 'none', m249 varchar(64) NOT NULL DEFAULT 'none', bizon varchar(64) NOT NULL DEFAULT 'none', p90 varchar(64) NOT NULL DEFAULT 'none', scar20 varchar(64) NOT NULL DEFAULT 'none', g3sg1 varchar(64) NOT NULL DEFAULT 'none',m4a1 varchar(64) NOT NULL DEFAULT 'none',m4a1_silencer varchar(64) NOT NULL DEFAULT 'none',ak47 varchar(64) NOT NULL DEFAULT 'none',aug varchar(64) NOT NULL DEFAULT 'none',galilar varchar(64) NOT NULL DEFAULT 'none',awp varchar(64) NOT NULL DEFAULT 'none',sg556 varchar(64) NOT NULL DEFAULT 'none',ump45 varchar(64) NOT NULL DEFAULT 'none',mp7 varchar(64) NOT NULL DEFAULT 'none',famas varchar(64) NOT NULL DEFAULT 'none',mp9 varchar(64) NOT NULL DEFAULT 'none',mac10 varchar(64) NOT NULL DEFAULT 'none',ssg08 varchar(64) NOT NULL DEFAULT 'none',nova varchar(64) NOT NULL DEFAULT 'none',xm1014 varchar(64) NOT NULL DEFAULT 'none',sawedoff varchar(64) NOT NULL DEFAULT 'none',mag7 varchar(64) NOT NULL DEFAULT 'none',elite varchar(64) NOT NULL DEFAULT 'none',deagle varchar(64) NOT NULL DEFAULT 'none',tec9 varchar(64) NOT NULL DEFAULT 'none',fiveseven varchar(64) NOT NULL DEFAULT 'none',cz75a varchar(64) NOT NULL DEFAULT 'none',glock varchar(64) NOT NULL DEFAULT 'none',usp_silencer varchar(64) NOT NULL DEFAULT 'none',p250 varchar(64) NOT NULL DEFAULT 'none',hkp2000 varchar(64) NOT NULL DEFAULT 'none',bayonet varchar(64) NOT NULL DEFAULT 'none',knife_gut varchar(64) NOT NULL DEFAULT 'none',knife_flip varchar(64) NOT NULL DEFAULT 'none',knife_m9_bayonet varchar(64) NOT NULL DEFAULT 'none',knife_karambit varchar(64) NOT NULL DEFAULT 'none',knife_tactical varchar(64) NOT NULL DEFAULT 'none',knife_butterfly varchar(64) NOT NULL DEFAULT 'none',c4 varchar(64) NOT NULL DEFAULT 'none',knife_falchion varchar(64) NOT NULL DEFAULT 'none',knife_push varchar(64) NOT NULL DEFAULT 'none',revolver varchar(64) NOT NULL DEFAULT 'none',favorite1 varch`

My databases.cfg looks like that:
`"Databases"
{
    "driver_default"        "mysql"

```
// When specifying "host", you may use an IP address, a hostname, or a socket file path

"default"
{
    "driver"            "default"
    "host"              "localhost"
    "database"          "sourcemod"
    "user"              "root"
    "pass"              ""
    //"timeout"         "0"
    //"port"            "0"
}

"storage-local"
{
    "driver"            "sqlite"
    "database"          "sourcemod-local"
}

"clientprefs"
{
    "driver"            "sqlite"
    "host"              "localhost"
    "database"          "clientprefs-sqlite"
    "user"              "root"
    "pass"              ""
    //"timeout"         "0"
    //"port"            "0"
}

"weaponpaints"
{
    "driver" "sqlite"
    "database" "weaponpaints"
}
```

}`

And my plugins list:
`01 "Basic Votes" (1.7.3-dev+5292) by AlliedModders LLC
  02 "Sound Commands" (1.7.3-dev+5292) by AlliedModders LLC
  03 "SwapTeam" (1.2.6) by Rogue - Originally by MistaGee and www.MyArena.ru
  04 "Client Preferences" (1.7.3-dev+5292) by AlliedModders LLC
  05 "QuickDefuse" (0.0.3) by pRED* and www.MyArena.ru
  06 "Anti-Flood" (1.7.3-dev+5292) by AlliedModders LLC
  07 "Basic Info Triggers" (1.7.3-dev+5292) by AlliedModders LLC
  08 "SM Knifes" (1.1) by Franc1sco franug
  09 "SM CS:GO Weapon Paints" (2.8.2 public version) by Franc1sco franug
  10 "Basic Ban Commands" (1.7.3-dev+5292) by AlliedModders LLC
  11 "Simple Chat Processor (Redux)" (1.1.5) by Simple Plugins, Mini
  12 "Radio Spam Block" (1.0.0) by exvel
  13 "Basic Commands" (1.7.3-dev+5292) by AlliedModders LLC
  14 "RoundEndSound" (1.1.2) by GoDtm666 (www.MyArena.ru)
  15 "Basic Comm Control" (1.7.3-dev+5292) by AlliedModders LLC
  16 "Fun Votes" (1.7.3-dev+5292) by AlliedModders LLC
  17 "Nextmap" (1.7.3-dev+5292) by AlliedModders LLC
  18 "Advertisements" (0.6 CSGO-1.1) by Tsunami (CSGO FIX Феникс)
  19 "Reserved Slots" (1.7.3-dev+5292) by AlliedModders LLC
  20 "Admin File Reader" (1.7.3-dev+5292) by AlliedModders LLC
  21 "Admin Menu" (1.7.3-dev+5292) by AlliedModders LLC
  22 "Basic Chat" (1.7.3-dev+5292) by AlliedModders LLC
  23 "Resetscore+" (1.5.1) by AlmazON
  24 "Welcome Sound" (1.0.1) by GoDtm666 (www.MyArena.ru)
  25 "MapChooser Extended" (1.9.1) by Powerlord, Zuko, and AlliedModders LLC
  26 "Player Commands" (1.7.3-dev+5292) by AlliedModders LLC
  27 "PermaMute" (0.1) by Ryan "FLOOR_MASTER" Mannion
  28 "Admin List" (1.2.0) by Fredd and www.MyArena.ru
  29 "SoDStats" (1.0.11) by ]SoD[ Frostbyte and www.MyArena.ru
  30 "Fun Commands" (1.7.3-dev+5292) by AlliedModders LLC
  31 "Players Votes" (1.5.0) by The Resident, pZv!
  32 "Weapon Restrict" (3.1.6) by Dr!fter
  33 "Admin Help" (1.7.3-dev+5292) by AlliedModders LLC
  34 "[VIP] GrenadeTrails" (1.0.1) by R1KO
  35 "[VIP] Tag" (1.0.0) by R1KO
  36 "[VIP] Regen HP" (1.0.4) by R1KO
  37 "[VIP] Throwing Knives" (1.0.4) by R1KO (original by meng, Bacardi)
  38 "[VIP] Kill Bonus" (1.0.0) by R1KO (skype: vova.andrienko1)
  39 "[VIP] Grenades (CS:GO)" (1.0.1 dev) by R1KO & sahapro33
  40 "[VIP] Anti Flash" (1.0.0) by R1KO
  41 "[VIP] Kick" (1.0.1) by R1KO (skype: vova.andrienko1)
  42 "[VIP] Core" (1.1.3 R) by R1KO (skype: vova.andrienko1)
  43 "[VIP] NEON (CSS/CSGO)" (1.0.3) by R1KO & Pheonix (‰7Феникс7‰)
  44 "[VIP] Test" (1.0.3) by R1KO (skype: vova.andrienko1)
  45 "Show Damage" (1.0.7) by exvel
  46 "Chat Colors CSGO" (1.2) by Phoenix - Феникс
  47 "Map Nominations" (1.7.3-dev+5283) by AlliedModders LLC`
I  believe you can help me! Thank you very much, your plugins are awesome! :P

**Comment by Franc1sco** [comment]
Check log errors

**Comment by appaKappaK** [comment]
ive got the same problem as well. Everytime i start up the server i see the same message he does. When i join it in the chat it says !cw to use.... but when i do !cw nothing pops up

**Comment by Franc1sco** [comment]
The command in this plugin is !ws and not !cw

**Comment by ghost** [comment]
I got The same Problem 1 month ago, just put the .sp in the plugins folder too, its worked for me i dont know why
