### ISSUE TITLE
new knife skin save

### ISSUE THREAD

**Issue by shtspk** [Franc1sco/Franug-Weapon_Paints#13]
The database dont save new knife skin

**Comment by Franc1sco** [comment]
I know it. Maybe in a future update I will add it.

**Comment by Danbardo** [comment]
Hey Franc1sco,
Thanks heaps for this plugin, it's awesome.
I noticed this problem as well and quickly patched it up,
shtspk,
If it's okay with Franc1sco, I have provided a link to the patched version of the plugin, all I did was add the new column to the weaponpaints table for the bowie knife.

https://www.dropbox.com/s/9zwiyoowsztrirk/franug_weaponpaints_private%20update.zip?dl=0

Thanks :)

**Comment by Franc1sco** [comment]
Thanks, added.
