### ISSUE TITLE
Skin not applying.

### ISSUE THREAD

**Issue by iSach** [Franc1sco/Franug-Weapon_Paints#17]
Hello,

I'd like to report an issue: The window pops up on the left, but when trying to apply skin, it doesn't work, it just doesn't show up.

Thanks in advance.

**Comment by Franc1sco** [comment]
Check log errors

**Comment by iSach** [comment]
Here's my log.
http://hastebin.com/kigodexiqo.md

**Comment by mikey548** [comment]
think i have same problem

**Comment by CSGOTheBlankMan** [comment]
I have the same problem too

**Comment by Franc1sco** [comment]
-Use the build 5298 -> http://www.sourcemod.net/downloads.php?branch=stable
-Use my !knife plugin -> https://github.com/Franc1sco/Franug-Knifes
-This cvar: sm_weaponpaints_zombiesv "1"
