### ISSUE TITLE
Problems with !ws and !knife

### ISSUE THREAD

**Issue by Deathmist1337** [Franc1sco/Franug-Weapon_Paints#19]
Hello, i am trying to install these plugins on my server, i have nothing but sourcemod, metamod and these mods, both of them are saying something about canno't set something with "FollowCSGOServerGuidelines" option enabled. Can i fix this?

!knife plugin:

`L 03/04/2016 - 18:42:54: [SM] Native "SetEntProp" reported: Cannot set m_iItemDefinitionIndex with "FollowCSGOServerGuidelines" option enabled.
L 03/04/2016 - 18:42:54: [SM] Displaying call stack trace for plugin "sm_franugknife.smx":
L 03/04/2016 - 18:42:54: [SM]   [0]  Line 50, E:\GitHub\Franug-Knifes\sm_franugknife.sp::OnPostWeaponEquip()
L 03/04/2016 - 18:42:54: [SM] Native "SetEntProp" reported: Cannot set m_iItemDefinitionIndex with "FollowCSGOServerGuidelines" option enabled.
L 03/04/2016 - 18:42:54: [SM] Displaying call stack trace for plugin "sm_franugknife.smx":
L 03/04/2016 - 18:42:54: [SM]   [0]  Line 50, E:\GitHub\Franug-Knifes\sm_franugknife.sp::OnPostWeaponEquip()`

!ws plugin

`L 03/04/2016 - 18:43:14: Query UPDATE weaponpaints SET usp_silencer = 'Fade (revolver)' WHERE steamid = 'STEAM_1:0:54614133';
L 03/04/2016 - 18:43:14: [SM] Native "SetEntProp" reported: Cannot set m_iItemIDLow with "FollowCSGOServerGuidelines" option enabled.
L 03/04/2016 - 18:43:14: [SM] Displaying call stack trace for plugin "franug_weaponpaints_private.smx":
L 03/04/2016 - 18:43:14: [SM]   [0]  Line 956, E:\GitHub\Franug-Weapon_Paints\franug_weaponpaints_private.sp::ChangePaint()
L 03/04/2016 - 18:43:14: [SM]   [1]  Line 1020, E:\GitHub\Franug-Weapon_Paints\franug_weaponpaints_private.sp::OnPostWeaponEquip()
L 03/04/2016 - 18:43:14: [SM] Native "SetEntProp" reported: Entity 267528 (267528) is invalid
L 03/04/2016 - 18:43:14: [SM] Displaying call stack trace for plugin "franug_weaponpaints_private.smx":
L 03/04/2016 - 18:43:14: [SM]   [0]  Line 941, E:\GitHub\Franug-Weapon_Paints\franug_weaponpaints_private.sp::Restore()
L 03/04/2016 - 18:43:14: [SM]   [1]  Line 723, E:\GitHub\Franug-Weapon_Paints\franug_weaponpaints_private.sp::DIDMenuHandler()`

It says this in the weaponpaints_1.log file:

`L 03/04/2016 - 18:32:48: Query CREATE TABLE IF NOT EXISTS weaponpaints (playername varchar(128) NOT NULL, steamid varchar(32) NOT NULL, last_accountuse int(64) NOT NULL, negev varchar(64) NOT NULL DEFAULT 'none', m249 varchar(64) NOT NULL DEFAULT 'none', bizon varchar(64) NOT NULL DEFAULT 'none', p90 varchar(64) NOT NULL DEFAULT 'none', scar20 varchar(64) NOT NULL DEFAULT 'none', g3sg1 varchar(64) NOT NULL DEFAULT 'none',m4a1 varchar(64) NOT NULL DEFAULT 'none',m4a1_silencer varchar(64) NOT NULL DEFAULT 'none',ak47 varchar(64) NOT NULL DEFAULT 'none',aug varchar(64) NOT NULL DEFAULT 'none',galilar varchar(64) NOT NULL DEFAULT 'none',awp varchar(64) NOT NULL DEFAULT 'none',sg556 varchar(64) NOT NULL DEFAULT 'none',ump45 varchar(64) NOT NULL DEFAULT 'none',mp7 varchar(64) NOT NULL DEFAULT 'none',famas varchar(64) NOT NULL DEFAULT 'none',mp9 varchar(64) NOT NULL DEFAULT 'none',mac10 varchar(64) NOT NULL DEFAULT 'none',ssg08 varchar(64) NOT NULL DEFAULT 'none',nova varchar(64) NOT NULL DEFAULT 'none',xm1014 varchar(64) NOT NULL DEFAULT 'none',sawedoff varchar(64) NOT NULL DEFAULT 'none',mag7 varchar(64) NOT NULL DEFAULT 'none',elite varchar(64) NOT NULL DEFAULT 'none',deagle varchar(64) NOT NULL DEFAULT 'none',tec9 varchar(64) NOT NULL DEFAULT 'none',fiveseven varchar(64) NOT NULL DEFAULT 'none',cz75a varchar(64) NOT NULL DEFAULT 'none',glock varchar(64) NOT NULL DEFAULT 'none',usp_silencer varchar(64) NOT NULL DEFAULT 'none',p250 varchar(64) NOT NULL DEFAULT 'none',hkp2000 varchar(64) NOT NULL DEFAULT 'none',bayonet varchar(64) NOT NULL DEFAULT 'none',knife_gut varchar(64) NOT NULL DEFAULT 'none',knife_flip varchar(64) NOT NULL DEFAULT 'none',knife_m9_bayonet varchar(64) NOT NULL DEFAULT 'none',knife_karambit varchar(64) NOT NULL DEFAULT 'none',knife_tactical varchar(64) NOT NULL DEFAULT 'none',knife_butterfly varchar(64) NOT NULL DEFAULT 'none',c4 varchar(64) NOT NULL DEFAULT 'none',knife_falchion varchar(64) NOT NULL DEFAULT 'none',knife_push varchar(64) NOT NULL DEFAULT 'none',revolver varchar(64) NOT NULL DEFAULT 'none',knife_survival_`

My databases.cfg file:

`"Databases"
{
    "driver_default"        "mysql"

```
// When specifying "host", you may use an IP address, a hostname, or a socket file path

"default"
{
    "driver"            "default"
    "host"              "localhost"
    "database"          "sourcemod"
    "user"              "root"
    "pass"              ""
    //"timeout"         "0"
    //"port"            "0"
}

"storage-local"
{
    "driver"            "sqlite"
    "database"          "sourcemod-local"
}

"clientprefs"
{
    "driver"            "sqlite"
    "host"              "localhost"
    "database"          "clientprefs-sqlite"
    "user"              "root"
    "pass"              ""
    //"timeout"         "0"
    //"port"            "0"
}

"weaponpaints"
{
    "driver" "sqlite"
    "database" "weaponpaints"
}
```

}`

**Comment by T3hFyrefly** [comment]
Okay so I figured it out, recently new versions of SourceMod have a safeguard to prevent plugins from using functions against Volvo's (selectively enforced) TOS. Though I doubt that would make any difference seeing how valve will ban you for even having the plugin in the disabled folder, or just have the tag "Knife" even if you never installed metamod or sourcemod, but that's besides the point.

Lucky for us the sourcemod devs are nice people, and have allowed us to disable this feature. What you have to do is edit the "core.cfg" located in the configs folder of sourcemod. For me it will be here "S:\SteamCMD\Server\go\csgo\addons\sourcemod\configs"

Open it with Notepad++ and scroll all the way to the bottom til you see something that says "FollowCSGOServerGuidelines" change that "yes" to a "no". And there you go, the skins and knive plugins are now working again. As an added bonus get a plugin that allows custom skins, and change your server tags to say "ScrewYouVolvo"

**Comment by Deathmist1337** [comment]
Thank you, works well. So, can i not get banned for using this in ONLY LAN and without the game server login tokens?

**Comment by T3hFyrefly** [comment]
I can't speak from experience on that one, but when you don't use a GSLT it uses the anon account and restricts it to lan only regardless of server settings. My GSLT was banned, but since then I've removed the GSLT settings on my server and it seems to still be functional. Valve didn't seem to ban my IP, or prevent my 2nd account from playing on GO servers or hosting any server in general. No VAC, Game, or Trade bans will appear on your profile page. Assuming you ain't advertising your server I believe you will be fine as long as no GSLT is assigned. But make sure to spread the word that GSLTs are evil.

**Comment by Deathmist1337** [comment]
Ok ty, i am running it on LAN and with no GSLT, no ban yet :) Gonna close this issue now.
