### ISSUE TITLE
help doesnt work

### ISSUE THREAD

**Issue by mikey548** [Franc1sco/Franug-Weapon_Paints#23]
when i choose a weapon it not applies to the weapon pls help
my error log: http://hastebin.com/raw/radixezige

**Comment by Franc1sco** [comment]
-Use the build 5298 -> http://www.sourcemod.net/downloads.php?branch=stable
-Use my !knife plugin -> https://github.com/Franc1sco/Franug-Knifes
-This cvar: sm_weaponpaints_zombiesv "1"
