### ISSUE TITLE
Bug with texture

### ISSUE THREAD

**Issue by LedoM1337** [Franc1sco/Franug-Weapon_Paints#24]
Hello!

I can only use !bayonet.If I choose another one i cant see textures.

Please help
LedoM

**Comment by Franc1sco** [comment]
-Use the build 5298 -> http://www.sourcemod.net/downloads.php?branch=stable
-Use my !knife plugin -> https://github.com/Franc1sco/Franug-Knifes
-This cvar: sm_weaponpaints_zombiesv "1"
