### ISSUE TITLE
Bug with this plugin and with the Knife Plugin  :( 

### ISSUE THREAD

**Issue by thxforhelp** [Franc1sco/Franug-Weapon_Paints#25]
i think i installed the knife and the WS plugin 
correctly.
 but i if i want to chage the knife i can only change to a bayonet ?!?! :? 
and if i  want to chage to another skin it dosen t work too i have the menu and so on but so skins :( 
i hope you can help me.

my console 

Failed to load gamerulescvars.txt, game rules cvars might not be reported to management tools.
Server is hibernating
No web api auth key specified - workshop downloads will be disabled.
maxplayers set to 64
ConVarRef cl_embedded_stream_video_playing doesn't point to an existing ConVar
Unknown command "cl_bobamt_vert"
Unknown command "cl_bobamt_lat"
Unknown command "cl_bob_lower_amt"
Unknown command "cl_viewmodel_shift_left_amt"
Unknown command "cl_viewmodel_shift_right_amt"
Unknown command "cl_teamid_min"
Unknown command "cl_teamid_max"
Unknown command "cl_teamid_overhead"
Unknown command "cl_teamid_overhead_maxdist"
Unknown command "cl_hudenable"
Unknown command "disp_modlimit_up"
Unknown command "r_anamorphic"
Unknown command "snd_surround"
Unknown command "rem"
Unknown command "rem"
Unknown command "cl_mouseenable"
Unknown command "rem"
Unknown command "rem"
Unknown command "rem"
Unknown command "rem"
Unknown command "rem"
Unknown command "rem"
Unknown command "rem"
Unknown command "rem"
Unknown command "rem"
1 demo(s) in loop
Deferring playdemo command!
Unknown command "sm_weaponpaints_c4"
Unknown command "sm_weaponpaints_saytimer"
Unknown command "sm_weaponpaints_roundtimer"
Unknown command "sm_weaponpaints_rmenu"
Unknown command "sm_weaponpaints_onlyadmin"
Cannot init steam datagram client, no Steam HTTP interface
L 04/08/2016 - 18:07:37: Config error (key: FollowCSGOServerGuidelines) (value: yes) P´
---- Host_NewGame ----
Missing map material: CS_HAVANA/CONCRETEFLOOR011A
Missing map material: CONCRETE/CONCRETEWALL059D
###### 

Map surf_ski_2_GO missing stringtable dictionary, don't ship this way!!!
Run with -stringtables on the command line or convar
stringtable_alwaysrebuilddictionaries enabled to build the string table
###### 

Host_NewGame on map surf_ski_2_GO
L 04/08/2016 - 18:07:37: -------- Mapchange to surf_ski_2_GO --------
CGameEventManager::AddListener: event 'teamplay_win_panel' unknown.
CGameEventManager::AddListener: event 'teamplay_restart_round' unknown.
CGameEventManager::AddListener: event 'arena_win_panel' unknown.
L 04/08/2016 - 18:07:38: [SM] Fatal error encountered parsing translation file "redsawpwiderestriction.phrases.txt"
L 04/08/2016 - 18:07:38: [SM] Error (line 0, column 0): Stream failed to open
L 04/08/2016 - 18:07:38: [admin-flatfile.smx] Error(s) detected parsing addons\sourcemod\configs\admin_overrides.cfg
L 04/08/2016 - 18:07:38: [admin-flatfile.smx](line 22) A property was declared outside of a section
GameTypes: missing mapgroupsSP entry for game type/mode (custom/custom).
GameTypes: missing mapgroupsSP entry for game type/mode (cooperative/cooperative).
GameTypes: missing mapgroupsSP entry for game type/mode (cooperative/coopmission).
bot_autodifficulty_threshold_high - 5.0
bot_autodifficulty_threshold_low - -2.0
bot_chatter - normal
bot_defer_to_human_goals - 0
bot_defer_to_human_items - 1
bot_difficulty - 1
bot_quota - 10
bot_quota_mode - normal
bot_allow_grenades - 1
bot_allow_pistols - 1
bot_allow_sub_machine_guns - 1
bot_allow_shotguns - 1
bot_allow_rifles - 1
bot_allow_snipers - 1
bot_allow_machine_guns - 1
sv_auto_adjust_bot_difficulty - 1
sv_bots_get_easier_each_win - 0
sv_bots_force_rebuy_every_round - 0
sv_bots_get_harder_after_each_wave - 0
mp_playercashawards - 1
cash_player_bomb_defused - 300
cash_player_bomb_planted - 300
cash_player_damage_hostage - -30
cash_player_interact_with_hostage - 150
cash_player_killed_enemy_default - 300
cash_player_killed_enemy_factor - 1
cash_player_killed_hostage - -1000
cash_player_killed_teammate - -300
cash_player_rescued_hostage - 1000
cash_player_respawn_amount - 0
cash_player_get_killed - 0
mp_teamcashawards - 1
cash_team_elimination_bomb_map - 3250
cash_team_elimination_hostage_map_t - 1000
cash_team_elimination_hostage_map_ct - 2000
cash_team_hostage_alive - 0
cash_team_hostage_interaction - 500
cash_team_loser_bonus - 1400
cash_team_loser_bonus_consecutive_rounds - 500
cash_team_planted_bomb_but_defused - 800
cash_team_rescued_hostage - 0
cash_team_terrorist_win_bomb - 3500
cash_team_win_by_defusing_bomb - 3250
cash_team_win_by_hostage_rescue - 3500
cash_team_win_by_time_running_out_bomb - 3250
cash_team_win_by_time_running_out_hostage - 3250
cash_team_survive_guardian_wave - 1000
mp_afterroundmoney - 0
mp_buytime - 90
mp_buy_anywhere - 0
mp_buy_during_immunity - 0
mp_startmoney - 800
mp_maxmoney - 16000
sv_buy_status_override - -1
mp_death_drop_defuser - 1
mp_death_drop_grenade - 2
mp_death_drop_gun - 1
mp_deathcam_skippable - 1
mp_defuser_allocation - 0
mp_give_player_c4 - 1
mp_free_armor - 0
mp_molotovusedelay - 15.0
mp_weapons_allow_zeus - 1
mp_weapons_allow_map_placed - 0
mp_weapons_glow_on_ground - 0
mp_ct_default_melee - weapon_knife
mp_ct_default_secondary - weapon_hkp2000
mp_ct_default_primary - 
mp_ct_default_grenades - 
mp_t_default_melee - weapon_knife
mp_t_default_secondary - weapon_glock
mp_t_default_primary - 
mp_t_default_grenades - 
mp_buy_allow_grenades - 1
mp_weapons_allow_typecount - 5
mp_freezetime - 6
mp_force_pick_time - 15
mp_halftime - 0
mp_match_can_clinch - 1
mp_maxrounds - 0
mp_roundtime - 5
mp_roundtime_defuse - 0
mp_roundtime_hostage - 0
mp_timelimit - 5
mp_warmuptime - 30
mp_warmuptime_all_players_connected - 60
mp_warmup_pausetimer - 0
mp_halftime_pausetimer - 0
mp_default_team_winner_no_objective - -1
mp_hostagepenalty - 10
mp_solid_teammates - 1
sv_allow_votes - 1
sv_alltalk - 0
sv_auto_full_alltalk_during_warmup_half_end - 1
sv_deadtalk - 0
sv_ignoregrenaderadio - 0
mp_teammates_are_enemies - 0
mp_damage_scale_ct_body - 1.0
mp_damage_scale_ct_head - 1.0
mp_damage_scale_t_body - 1.0
mp_damage_scale_t_head - 1.0
mp_friendlyfire - 0
ff_damage_reduction_bullets - 0.1
ff_damage_reduction_grenade - 0.25
ff_damage_reduction_grenade_self - 1
ff_damage_reduction_other - 0.25
mp_limitteams - 2
spec_freeze_panel_extended_time - 0.0
spec_freeze_time - 2.0
mp_forcecamera - 1
mp_respawn_immunitytime - 4.0
mp_respawn_on_death_t - 0
mp_respawn_on_death_ct - 0
mp_display_kill_assists - 1
mp_use_respawn_waves - 0
mp_respawnwavetime_ct - 10.0
mp_respawnwavetime_t - 10.0
mp_randomspawn - 0
mp_randomspawn_los - 1
mp_randomspawn_dist - 0
mp_radar_showall - 0
mp_force_assign_teams - 0
sv_gravity - 800
sv_accelerate - 5.5
sv_stopspeed - 80
sv_airaccelerate - 12
sv_wateraccelerate - 10
sv_waterfriction - 1
sv_friction - 5.2
sv_bounce - 0
sv_maxvelocity - 3500
sv_maxspeed - 320
sv_bot_buy_grenade_chance - 33
sv_bot_buy_smoke_weight - 1
sv_bot_buy_flash_weight - 1
sv_bot_buy_decoy_weight - 1
sv_bot_buy_molotov_weight - 1
sv_bot_buy_hegrenade_weight - 6
sv_guardian_min_wave_for_heavy - 0
sv_guardian_max_wave_for_heavy - 0
sv_guardian_heavy_count - 0
sv_guardian_heavy_all - 0
mp_ggprogressive_round_restart_delay - 15.0
mp_ggtr_bomb_defuse_bonus - 1.0
mp_ggtr_bomb_detonation_bonus - 1.0
mp_ggtr_bomb_pts_for_flash - 4
mp_ggtr_bomb_pts_for_he - 3
mp_ggtr_bomb_pts_for_molotov - 5
mp_ggtr_bomb_pts_for_upgrade - 2.0
mp_ggtr_bomb_respawn_delay - 0.0
mp_ggtr_end_round_kill_bonus - 1
mp_ggtr_halftime_delay - 0.0
mp_ggtr_last_weapon_kill_ends_half - 0
sv_arms_race_vote_to_restart_disallowed_after - 0
mp_coop_force_join_ct - 0
bot_allow_rogues - 1
mp_guardian_special_kills_needed - 10
mp_guardian_special_weapon_needed - awp
mp_guardian_player_dist_min - 1300
mp_guardian_player_dist_max - 2000
mp_guardian_target_site - -1
mp_hostages_spawn_force_positions - 
mp_hostages_spawn_same_every_round - 1
mp_guardian_bot_money_per_wave - 800
sv_disable_show_team_select_menu - 0
mp_hostages_max - 2
spec_replay_enable - 0
mp_round_restart_delay - 7.0
mp_coopmission_bot_difficulty_offset - 0
sv_duplicate_playernames_ok - 0
mp_anyone_can_pickup_c4 - 0
mp_c4_cannot_be_defused - 0
mp_c4timer - 40
mp_coopmission_mission_number - 0
weapon_reticle_knife_show - 0
mp_death_drop_c4 - 1
Executing dedicated server config file
exec: couldn't exec server.cfg
exec: couldn't exec gamemode_casual_server.cfg
PlayerModelInfo: missing terrorist models for map surf_ski_2_GO. Adding the default model tm_phoenix.
PlayerModelInfo: missing counter-terrorist models for map surf_ski_2_GO. Adding the default model ctm_st6.
Couldn't find any entities named ssg08_equip1, which point_template ssg08_equip_template1 is specifying.
Couldn't find any entities named ssg08_equip1, which point_template ssg08_equip_template1 is specifying.
Precache called on a point_template that has no templates: ssg08_equip_template1
Precache called on a point_template that has no templates: ssg08_equip_template1
Commentary: Could not find commentary data file 'maps/surf_ski_2_GO_commentary.txt'. 
Error parsing BotProfile.db - unknown attribute 'Rank'
Error parsing BotProfile.db - unknown attribute 'Rank'
Error parsing BotProfile.db - unknown attribute 'Rank'
Error parsing BotProfile.db - unknown attribute 'Rank'
Error parsing BotProfile.db - unknown attribute 'Rank'
Error parsing BotProfile.db - unknown attribute 'Rank'
Error parsing BotProfile.db - unknown attribute 'Rank'
Error parsing BotProfile.db - unknown attribute 'Rank'
Initializing Steam libraries for secure Internet server

VAC secure mode is activated.
GC Connection established for server version 314, instance idx 1
L 04/08/2016 - 18:07:45: Query CREATE TABLE IF NOT EXISTS weaponpaints (playername varchar(128) NOT NULL, steamid varchar(32) NOT NULL, last_accountuse int(64) NOT NULL, negev varchar(64) NOT NULL DEFAULT 'none', m249 varchar(64) NOT NULL DEFAULT 'none', bizon varchar(64) NOT NULL DEFAULT 'none', p90 varchar(64) NOT NULL DEFAULT 'none', scar20 varchar(64) NOT NULL DEFAULT 'none', g3sg1 varchar(64) NOT NULL DEFAULT 'none',m4a1 varchar(64) NOT NULL DEFAULT 'none',m4a1_silencer varchar(64) NOT NULL DEFAULT 'none',ak47 varchar(64) NOT NULL DEFAULT 'none',aug varchar(64) NOT NULL DEFAULT 'none',galilar varchar(64) NOT NULL DEFAULT 'none',awp varchar(64) NOT NULL DEFAULT 'none',sg556 varchar(64) NOT NULL DEFAULT 'none',ump45 varchar(64) NOT NULL DEFAULT 'none',mp7 varchar(64) NOT NULL DEFAULT 'none',famas varchar(64) NOT NULL DEFAULT 'none',mp9 varchar(64) NOT NULL DEFAULT 'none',mac10 varchar(64) NOT NULL DEFAULT 'none',ssg08 varchar(64) NOT NULL DEFAULT 'none',nova varchar(64) NOT NULL DEFAULT 'none',xm1014 varchar(64) NOT NULL DEFAULT 'none',sawedoff varchar(64) NOT NULL DEFAULT 'none',mag7 varchar(64) NOT NULL DEFAULT 'none',elite varchar(64) NOT NULL DEFAULT 'none',deagle varchar(64) NOT NULL DEFAULT 'none',tec9 varchar(64) NOT NULL DEFAULT 'none',fiveseven varchar(64) NOT NULL DEFAULT 'none',cz75a varchar(64) NOT NULL DEFAULT 'none',glock varchar(64) NOT NULL DEFAULT 'none',usp_silencer varchar(64) NOT NULL DEFAULT 'none',p250 varchar(64) NOT NULL DEFAULT 'none',hkp2000 varchar(64) NOT NULL DEFAULT 'none',bayonet varchar(64) NOT NULL DEFAULT 'none',knife_gut varchar(64) NOT NULL DEFAULT 'none',knife_flip varchar(64) NOT NULL DEFAULT 'none',knife_m9_bayonet varchar(64) NOT NULL DEFAULT 'none',knife_karambit varchar(64) NOT NULL DEFAULT 'none',knife_tactical varchar(64) NOT NULL DEFAULT 'none',knife_butterfly varchar(64) NOT NULL DEFAULT 'none',c4 varchar(64) NOT NULL DEFAULT 'none',knife_falchion varchar(64) NOT NULL DEFAULT 'none',knife_push varchar(64) NOT NULL DEFAULT 'none',revolver varchar(64) NOT NULL DEFAULL 04/08/2016 - 18:07:45: Log file closed.
L 04/08/2016 - 18:07:45: Error log file session closed.

my Plugins 

[SM] Listing 23 plugins:
  01 "[CSS/CS:GO] AbNeR Bunny Hoping" (2.0) by AbNeR_CSS
  02 "Admin File Reader" (1.7.3-dev+5302) by AlliedModders LLC
  03 "Admin Help" (1.7.3-dev+5302) by AlliedModders LLC
  04 "Admin Menu" (1.7.3-dev+5302) by AlliedModders LLC
  05 "Anti-Flood" (1.7.3-dev+5302) by AlliedModders LLC
  06 "Basic Ban Commands" (1.7.3-dev+5302) by AlliedModders LLC
  07 "Basic Chat" (1.7.3-dev+5302) by AlliedModders LLC
  08 "Basic Comm Control" (1.7.3-dev+5302) by AlliedModders LLC
  09 "Basic Commands" (1.7.3-dev+5302) by AlliedModders LLC
  10 "Basic Info Triggers" (1.7.3-dev+5302) by AlliedModders LLC
  11 "Basic Votes" (1.7.3-dev+5302) by AlliedModders LLC
  12 "Client Preferences" (1.7.3-dev+5302) by AlliedModders LLC
  13 "SM CS:GO Weapon Paints" (2.8.3 public version) by Franc1sco franug
  14 "Fun Commands" (1.7.3-dev+5302) by AlliedModders LLC
  15 "Fun Votes" (1.7.3-dev+5302) by AlliedModders LLC
  16 "Nextmap" (1.7.3-dev+5302) by AlliedModders LLC
  17 "Player Commands" (1.7.3-dev+5302) by AlliedModders LLC
  18 "CS:GO Redie" (2.4) by Pyro, originally by MeoW
  19 "Red's AWP Wide Restriction" (2.2.0) by RedSword
  20 "Reserved Slots" (1.7.3-dev+5302) by AlliedModders LLC
  21 "Knife Upgrade" (2.5.7) by Klexen
  22 "RealBhop" (1.1.1) by SeriTools
  23 "Sound Commands" (1.7.3-dev+5302) by AlliedModders LLC

**Comment by Franc1sco** [comment]
Buy the private version from me!

**Comment by thxforhelp** [comment]
*_Thx <3 *_
