### ISSUE TITLE
StatTrak Unknown User

### ISSUE THREAD

**Issue by kuhaufleitung** [Franc1sco/Franug-Weapon_Paints#26]
There is a problem with the StatTrak Counter. It always shows Unknown User.
In one of the older Versions it showed in the bottom right corner next to your ammo the stat counter.
Is there a way to re-enable that? I looked at the source code from 1.6.4 and 2.8.3 but I didnt find the difference.
It would be great if you fix this.
Thank You

//Edit: Is it because i sold all my skins? https://forums.alliedmods.net/showpost.php?p=2285210&postcount=213

**Comment by Franc1sco** [comment]
I don use the StatTrak feature in my servers but maybe some update can be break it.

**Comment by tzu2770** [comment]
How to use wp and knife without a server ban?

**Comment by kuhaufleitung** [comment]
thanks for your response
