### ISSUE TITLE
Cant install it

### ISSUE THREAD

**Issue by xxfeli** [Franc1sco/Franug-Weapon_Paints#27]
Hey, 
i wanted to install your Plugins on my server but it didnt work, even with YT videos. I have my Server on Gportal, is that the Problem?

Thx for help already,
Felix

**Comment by Franc1sco** [comment]
-Use the build 5298 -> http://www.sourcemod.net/downloads.php?branch=stable
-Use my !knife plugin -> https://github.com/Franc1sco/Franug-Knifes
-This cvar: sm_weaponpaints_zombiesv "1"
