### ISSUE TITLE
No Menu?

### ISSUE THREAD

**Issue by koszmar132** [Franc1sco/Franug-Weapon_Paints#28]
I installed both plugins !sw and !knife. the knife plugin works fine but using !ws on the server doesn't shoe me the menu to display skins. I already did the the sourcemod 5298 that you recommened to other people but this is what caused the menu not to work.

**Comment by Franc1sco** [comment]
Check log errors then

**Comment by iGreen123** [comment]
you should add this to your databases.cfg ->

```
    "weaponpaints"
    {
            "driver" "sqlite"
            "database" "weaponpaints"
    }
```
