### ISSUE TITLE
doesnt load the skins

### ISSUE THREAD

**Issue by jonern99** [Franc1sco/Franug-Weapon_Paints#31]
Hello. just got a csgo server and installed the !ws plugin, whenever i type !ws in chat the menu pops up, but when i try to select a skin, it doesnt change.

**Comment by Franc1sco** [comment]
-Use the build 5298 -> http://www.sourcemod.net/downloads.php?branch=stable
-Use my !knife plugin -> https://github.com/Franc1sco/Franug-Knifes
-This cvar: sm_weaponpaints_zombiesv "1"

**Comment by iGreen123** [comment]
build 5303 is not good?

**Comment by launchpad4life** [comment]
If you want to use 5303, you have to open your sm config (addons/sourcemod/configs/config.cfg)
and change
"FollowCSGOServerGuidelines" "Yes"
to
"FollowCSGOServerGuidelines" "no"
