### ISSUE TITLE
sourcemod 5303 should we use it?

### ISSUE THREAD

**Issue by iGreen123** [Franc1sco/Franug-Weapon_Paints#33]
hi, i see that on sourcemod 5303 the update is like this:

Really fix FollowCSGOServerGuidelines setting being ignored in SDKTools (always on) (bug 6480).

will this plugin work if we update to this version of sourcemod?
btw my server account token got banned, i didnt advertise the plugin on sv tags and it was only available for admins, is there anything to do so the token doesnt get banned? i changed in core 
"FollowCSGOServerGuidelines" "no"
"BlockBadPlugins"   "no"

maybe anything else?
also before update i unloaded the plugins and deleted them (completly) so that when i make the update valve doesnt see them but still the token got banned :(

**Comment by Franc1sco** [comment]
For full support buy the private version.

**Comment by iGreen123** [comment]
can i have you steam profile to add you on friend so we can talk about the price? thank you very much

**Comment by Franc1sco** [comment]
http://steamcommunity.com/id/franug

**Comment by iGreen123** [comment]
i added you but you need to accept :)
thank you
