### ISSUE TITLE
Is it possible to change weapon names?

### ISSUE THREAD

**Issue by moderatorman** [Franc1sco/Franug-Weapon_Paints#39]
I want to change weapon names, and I know there aren't any menu items for doing this. Would it be possible through the language file? Or should I change it in the knifes cfg file?

Also, would you happen to know where I could find a surf gamemode for my server?

**Comment by kuhaufleitung** [comment]
You can find the surf gamemode here: https://forums.alliedmods.net/showthread.php?t=264498
Maybe it´s possible with "SetEntProp" and "m_szCustomName" to change weapon names as name tags.
