### ISSUE TITLE
Skins not applying

### ISSUE THREAD

**Issue by Orangile** [Franc1sco/Franug-Weapon_Paints#42]
When I install the plugin and then go to CSGO and type !ws I can see the list but when I press some paint it says in chat that i did that but then closes the menu and i dont have the skin on my weapons. same thing with your knife plugin it doesnt give me the knife it just closes the menu.

**Comment by NootOverLord** [comment]
here m8 try this (copy and paste from author)
-Use the build 5298 -> http://www.sourcemod.net/downloads.php?branch=stable
-Use my !knife plugin -> https://github.com/Franc1sco/Franug-Knifes
-This cvar: sm_weaponpaints_zombiesv "1"
again these are not my solutions thank Franc1sco
