### ISSUE TITLE
private and public

### ISSUE THREAD

**Issue by iGreen123** [Franc1sco/Franug-Weapon_Paints#48]
for private version u dont get ur token banned
for public version u get ur token banned

is that right or am i missing smth?
thank you for your answer

**Comment by Franc1sco** [comment]
The private version you can use always like in my servers http://bans.cola-team.com/index.php?p=servers

For more info, buy the private version.

**Comment by iGreen123** [comment]
well my friend, i need the answer in order to buy it, right?
