### ISSUE TITLE
I put on the chat !ws and dont appear nothing.

### ISSUE THREAD

**Issue by Claush17** [Franc1sco/Franug-Weapon_Paints#52]
I put on the chat !ws and dont appear nothing pls help! and the same with the knife plugin!

**Comment by laxr404** [comment]
@ClaushPT  Did you make yourself admin on your server and is sourcemod updated?

**Comment by PsiClown1** [comment]
@officialenim I have the same issue I'm admin on server and latest sourcemod

**Comment by incizzle** [comment]
dont run latest source mod

**Comment by incizzle** [comment]
-Use the build 5298 -> http://www.sourcemod.net/downloads.php?branch=stable
-Use my !knife plugin -> https://github.com/Franc1sco/Franug-Knifes
-This cvar: sm_weaponpaints_zombiesv "1
PS: From Owner Of plugin :)

**Comment by Claush17** [comment]
@officialenim yes im admin in the servver

**Comment by Claush17** [comment]
@incizzle build 5298 is not very old? and dont exist 5297 , 5299

**Comment by PsiClown1** [comment]
@ClaushPT can you link me to build 5298?

**Comment by Claush17** [comment]
@PsiClown1 dont exist the build 5298

**Comment by PsiClown1** [comment]
@ClaushPT oh ok 
@incizzle what build should i use?

**Comment by Claush17** [comment]
or the 1.7 Branch 5298 exist

**Comment by PsiClown1** [comment]
@incizzle I managed to make the !knife work now the problem was the core.cfg I had to change follow rules etc. Thanks for the help I'm now just trying to figure out how to make !ws work

**Comment by laxr404** [comment]
I am using "sourcemod-1.8.0-git5919-windows" and it works properly.

**Comment by PsiClown1** [comment]
@officialenim Thanks for the info I'll try that build
