### ISSUE TITLE
no answer on steam =/

### ISSUE THREAD

**Issue by iGreen123** [Franc1sco/Franug-Weapon_Paints#55]
man, i added you on steam, i want to buy the private version, i wrote to you like 3 or 4 times, you didnt answer me, now i dont see on friends list, whats  up with this? at least put the private version public then if you dont want to sell it =/

**Comment by Franc1sco** [comment]
Tell me your profile url

**Comment by iGreen123** [comment]
https://steamcommunity.com/id/igreen_elite
i really hope we can fix this because all my players are crazy about this !ws !knife :D

**Comment by Franc1sco** [comment]
I am available now in steam.
