### ISSUE TITLE
Updated Skin List.

### ISSUE THREAD

**Issue by maxofsteam** [Franc1sco/Franug-Weapon_Paints#57]
I was wondering if I could get the updated csgo_wpaints.cfg file with all the new skins. 

Thanks
-max

http://steamcommunity.com/id/okayjanai

**Comment by GmanWisdom** [comment]
yes plz would love the new skins from gamma 2 and would love it if u could just update it to the latest because for mine i dont even have gamma 1 stuff. Thanks great plugin just needs to be updated

**Comment by rogeraabbccdd** [comment]
you can get skin id at csgo/scripts/items/items_game.txt

**Comment by GmanWisdom** [comment]
nah i want to buy it is wat i mean

**Comment by AkshayBhanawala** [comment]
[csgo_wpaints.zip](https://github.com/Franc1sco/Franug-Weapon_Paints/files/443293/csgo_wpaints.zip)
I Updated & Organised By name.
I Hope this Have All the Data Correct
If Any Error Contact at
http://steamcommunity.com/id/TH3-AZ

**Comment by rogeraabbccdd** [comment]
just use pull request
