### ISSUE TITLE
Franug plugin list blocker error

### ISSUE THREAD

**Issue by SamDude** [Franc1sco/Franug-Weapon_Paints#66]
Hello franug. You told me on steam to open a issue here.

A friend bought the plugin and got this error in console:

L 10/26/2016 - 21:26:20: [SM] Exception reported: Failed to find offset for ClientPrintf
L 10/26/2016 - 21:26:20: [SM] Blaming: sm_plugins_block.smx
L 10/26/2016 - 21:26:20: [SM] Call stack trace:
L 10/26/2016 - 21:26:20: [SM]   [0] SetFailState
L 10/26/2016 - 21:26:20: [SM]   [1] Line 66, E:\GitHub\BlockSMPlugins\scripting\sm_plugins_block.sp::StartPlugin
L 10/26/2016 - 21:26:20: [SM]   [2] Line 48, E:\GitHub\BlockSMPlugins\scripting\sm_plugins_block.sp::OnPluginStart
L 10/26/2016 - 21:26:20: [SM] Unable to load plugin "sm_plugins_block.smx": Error detected in plugin startup (see error logs)

Thats all error logs.

Which is the problem? Did you miss some files when you sent to him the plugin?

He also installed DHooks

And also in translations he have: sm_plugins_block.phrases.txt

Thats all.

sm_plugins_block.phrases.txt is that

"Phrases"
{
    "NoChance"
    {
        "en"    "SERVER"
        "es"    "SERVER"
    }
}

Thats all.

**Comment by Franc1sco** [comment]
This is not the place for that xD
