### ISSUE TITLE
glove case

### ISSUE THREAD

**Issue by iGreen123** [Franc1sco/Franug-Weapon_Paints#69]
hi francisco, can you pleaes tell how to add glove case to public version ? thank you very much

**Comment by Franc1sco** [comment]
Buy the private version and you will have that. The public version not have support

**Comment by iGreen123** [comment]
i understand there is no support but you could atleast update the public version, also i can give you all my inventory if you can give me the private version, if you accept then add me: http://steamcommunity.com/id/igreen_elite
