### ISSUE TITLE
Revolver doesn't work

### ISSUE THREAD

**Issue by pito11** [Franc1sco/Franug-Weapon_Paints#7]
When I use Revolver instead Desert Eagle and I will choose skin for R8, then I receive Deagle. How can I do ?

**Comment by Franc1sco** [comment]
Be sure that you use the latest version from here https://github.com/Franc1sco/Franug-Weapon_Paints/archive/master.zip

**Comment by pito11** [comment]
I'm sure.

**Comment by Franc1sco** [comment]
Check your plugin list. Some plugin maybe cause conflict.﻿
