### ISSUE TITLE
Errors weaponpaints

### ISSUE THREAD

**Issue by fakeoff0** [Franc1sco/Franug-Weapon_Paints#76]
hello Franc1sco! can u fix pls?
L 04/05/2017 - 09:01:37: [SM] Exception reported: NULL not allowed
L 04/05/2017 - 09:01:37: [SM] Blaming: franug_weaponpaints_private.smx
L 04/05/2017 - 09:01:37: [SM] Call stack trace:
L 04/05/2017 - 09:01:37: [SM]   [0] EquipPlayerWeapon
L 04/05/2017 - 09:01:37: [SM]   [1] Line 926, franug_weaponpaints_private.sp::Restore
L 04/05/2017 - 09:01:37: [SM]   [2] Line 713, franug_weaponpaints_private.sp::DIDMenuHandler
L 04/05/2017 - 09:06:21: [SM] Exception reported: NULL not allowed
L 04/05/2017 - 09:06:21: [SM] Blaming: franug_weaponpaints_private.smx

**Comment by Franc1sco** [comment]
Buy the private version from me for get support.
