### ISSUE TITLE
problem((

### ISSUE THREAD

**Issue by RodyaUshakov** [Franc1sco/Franug-Weapon_Paints#77]
L 04/26/2017 - 14:23:03: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 04/26/2017 - 14:23:03: [SM] Blaming: franug_weaponpaints_public.smx
L 04/26/2017 - 14:23:03: [SM] Call stack trace:
L 04/26/2017 - 14:23:03: [SM]   [0] SQL_TQuery
L 04/26/2017 - 14:23:03: [SM]   [1] Line 1100, E:\GitHub\Franug-Weapon_Paints\franug_weaponpaints_public.sp::CheckSteamID
L 04/26/2017 - 14:23:03: [SM]   [2] Line 1089, E:\GitHub\Franug-Weapon_Paints\franug_weaponpaints_public.sp::OnClientPostAdminCheck
L 04/26/2017 - 14:23:22: [SM] Exception reported: Invalid database Handle 0 (error: 4)

**Comment by Franc1sco** [comment]
Use sourcemod 1.8

Not use sourcemod 1.9

**Comment by Franc1sco** [comment]
Buy private version for get support.
