### ISSUE TITLE
Got Community Banned with that :D

### ISSUE THREAD

**Issue by iSach** [Franc1sco/Franug-Weapon_Paints#80]
Installed it on my server, like 1 week later, 2-week ban from CS:GO (huge downrank), and permanent ban from creating any community server on any game! great :> Still bannable with the current version?

(btw, just tested it as an admin, didn't put in tags, wanted to try a knife before buying it)

**Comment by Franc1sco** [comment]
Only clients that buy the private version from me are protected of receive a ban.

**Comment by iSach** [comment]
there was no private version when using it, just warning people as it's not clearly indicated imo the ban risk, it's really annoying for me to host my servers now

**Comment by iSach** [comment]
btw, how much is it usually for the private version?

**Comment by Franc1sco** [comment]
Contact in steam http://steamcommunity.com/id/franug
