### ISSUE TITLE
[RESOLVED] Star on every Weapon

### ISSUE THREAD

**Issue by aequabit** [Franc1sco/Franug-Weapon_Paints#9]
Hey dude!

When I apply a skin to a gun, the "★" is shown in front of every weapon name. How to fix that?

**Comment by joao-mambelli** [comment]
That is normal, this is the quality of the weapon...

Ps: your server will be banned using it

**Comment by aequabit** [comment]
It won't since it's private.

**Comment by joao-mambelli** [comment]
What do you mean with private?

**Comment by aequabit** [comment]
you need to connect through a website.
